### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by pohly** [wallento/sungrow-websocket#3]
This library and command line works fine with my SunGrow SG15RT and SG5.0RT (with some oddity, see [separate issue](https://github.com/wallento/sungrow-websocket/issues/2)), thanks a lot for your work!

Are you aware of anyone who has used this library to poll and to publish it via MQTT? I don't want to reinvent the wheel.

Would that be acceptable as a feature for sungrow-websocket  itself?

**Comment by wallento** [comment]
I would love it. I don't need it myself, but every addition is highly appreciated!

**Comment by pohly** [comment]
https://github.com/bohdan-s/SunGather also worked for me and already has MQTT support - I'll probably just use that.
